format = """
[┌─](bold green)$directory$git_branch$ruby$python$nodejs$fill$battery[─┐](bold green)
[└─](bold green)$time$character"""

[fill]
symbol = "─"
style = "bold green"

[directory]
truncation_length = 4
format = "[$path]($style) "
style = "bold cyan"

[git_branch]
format = "on [$branch]($style) "

[ruby]
format = "[ruby $version]($style) "

[python]
format = "[py $version($virtualenv)]($style) "

[nodejs]
format = "[node $version]($style) "

[time]
disabled = false
time_format = "%H:%M"
format = "[\\($time\\)─]($style)"
style = "bold yellow"

[battery]
format = "[\\($percentage\\)─]($style)"
display = [
  { threshold = 20, style = "bold red" },
  { threshold = 100, style = "bold green" },
]
